; 规则集定义
ruleset=🌐直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/LocalAreaNetwork.list
ruleset=♻️代理,https://raw.githubusercontent.com/captainp9/clash-config/refs/heads/main/config/PersonalProxy.list
ruleset=🌐直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/UnBan.list
ruleset=⛔Ban,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/BanAD.list
ruleset=⛔Ban,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/BanProgramAD.list
ruleset=⛔Ban,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/BanEasyPrivacy.list
ruleset=⛔Ban,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/BanEasyList.list
ruleset=⛔Ban,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/BanEasyListChina.list
ruleset=🌐直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/GoogleCN.list
ruleset=🌐直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/SteamCN.list
ruleset=💻Github,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Github.list
ruleset=🎥AppleTV,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/AppleTV.list
ruleset=📹YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/YouTube.list
ruleset=🎬Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Netflix.list
ruleset=🎞️DisneyPlus,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/DisneyPlus.list
ruleset=🗺️Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Google.list
ruleset=📷Instagram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Instagram.list
ruleset=☁️Onedrive,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/OneDrive.list
ruleset=🕹️Steam,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Steam.list
ruleset=🎮Sony,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Sony.list
ruleset=🍎Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Apple.list
ruleset=🪟Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Microsoft.list
ruleset=⚡Speedtest,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Speedtest/Speedtest.list
ruleset=♻️代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ProxyGFWlist.list

ruleset=Others,[]FINAL


; 策略组定义
custom_proxy_group=♻️代理`select`[]🇯🇵日本自动`[]🇭🇰香港自动`[]🇸🇬新加坡自动`[]🇺🇸美国自动`[]🚀手动选择`[]DIRECT
custom_proxy_group=⚡Speedtest`select`[]🇯🇵日本自动`[]🇭🇰香港自动`[]🇸🇬新加坡自动`[]🇺🇸美国自动`[]🚀手动选择`[]DIRECT
custom_proxy_group=🌐直连`select`[]DIRECT`[]🚀手动选择
custom_proxy_group=⛔Ban`select`[]REJECT`[]DIRECT
custom_proxy_group=💻Github`select`[]🇭🇰香港自动`[]🇺🇸美国自动`[]🚀手动选择`[]DIRECT
custom_proxy_group=🎥AppleTV`select`[]🇺🇸美国自动`[]🚀手动选择
custom_proxy_group=📹YouTube`select`[]🇭🇰香港自动`[]🇯🇵日本自动`[]🇸🇬新加坡自动`[]🇺🇸美国自动`[]🚀手动选择
custom_proxy_group=🎬Netflix`select`[]🇭🇰香港自动`[]🇯🇵日本自动`[]🇸🇬新加坡自动`[]🇺🇸美国自动`[]🚀手动选择
custom_proxy_group=🎞️DisneyPlus`select`[]🇭🇰香港自动`[]🇯🇵日本自动`[]🇸🇬新加坡自动`[]🇺🇸美国自动`[]🚀手动选择
custom_proxy_group=🗺️Google`select`[]🇭🇰香港自动`[]🇺🇸美国自动`[]🚀手动选择
custom_proxy_group=📷Instagram`select`[]🇭🇰香港自动`[]🇺🇸美国自动`[]🚀手动选择
custom_proxy_group=☁️Onedrive`select`[]🇺🇸美国自动`[]🚀手动选择
custom_proxy_group=🕹️Steam`select`[]🇭🇰香港自动`[]🇯🇵日本自动`[]🇺🇸美国自动`[]🚀手动选择
custom_proxy_group=🎮Sony`select`[]🇭🇰香港自动`[]🇯🇵日本自动`[]🇺🇸美国自动`[]🚀手动选择
custom_proxy_group=🍎Apple`select`[]DIRECT`[]🇺🇸美国自动`[]🚀手动选择
custom_proxy_group=🪟Microsoft`select`[]DIRECT`[]🇺🇸美国自动`[]🚀手动选择
custom_proxy_group=Others`select`[]DIRECT`[]🚀手动选择

; custom_proxy_group=
; custom_proxy_group=
; custom_proxy_group=
; custom_proxy_group=
; custom_proxy_group= 
; custom_proxy_group=


custom_proxy_group=🚀手动选择`select`.*
custom_proxy_group=🇭🇰香港自动`url-test`(?=.*(HKG))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇯🇵日本自动`url-test`(?=.*(JPN))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇸🇬新加坡自动`url-test`(?=.*(SGP))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇺🇸美国自动`url-test`(?=.*(USA))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🌏其他地区`select`(?!.*(HKG|JPN|SGP|USA))




; 启动自定义规则集
enable_rule_generator=true
overwrite_original_rules=true
