; 规则集定义

ruleset=🌐直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/LocalAreaNetwork.list
ruleset=🌐直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/UnBan.list

ruleset=⛔Ban,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/BanAD.list
ruleset=💻Github,
ruleset=🎥AppleTV,
ruleset=📹YouTube,
ruleset=🎬Netflix,
ruleset=🎞️DisneyPlus
ruleset=🈲Adult,
ruleset=🍎Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Apple.list
ruleset=Others,[]FINAL


; 策略组定义

custom_proxy_group=🌐直连`select`[]DIRECT`🚀手动选择
custom_proxy_group=⛔Ban`select`[]REJECT`[]DIRECT
custom_proxy_group=💻Github
custom_proxy_group=🎥AppleTV`select`[]🇺🇸美国自动`[]🚀手动选择
custom_proxy_group=📹YouTube`select`[]🇭🇰香港自动`[]🇯🇵日本自动`[]🇸🇬新加坡自动`[]🇺🇸美国自动`[]🚀手动选择
custom_proxy_group=🎬Netflix,
custom_proxy_group=🎞️DisneyPlus,
custom_proxy_group=🈲Adult
custom_proxy_group=🍎Apple`select`[]DIRECT`[]🇺🇸美国自动`[]🚀手动选择

; custom_proxy_group=
; custom_proxy_group=
; custom_proxy_group=
; custom_proxy_group=
; custom_proxy_group= 
; custom_proxy_group=


custom_proxy_group=🚀手动选择`select`.*
custom_proxy_group=🇭🇰香港自动`url-test`(?=.*(HKG))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇯🇵日本自动`url-test`(?=.*(JPN))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇸🇬新加坡自动`url-test`(?=.*(SGP))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇺🇸美国自动`url-test`(?=.*(USA))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🌏其他地区`select`(?!.*(HKG|JPN|SGP|USA))




; 启动自定义规则集
enable_rule_generator=true
overwrite_original_rules=true
